{{- if and (eq .Values.global.cloudProvider "gcp") (tpl (.Values.backendPolicy.enabled | toString) .) }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "care-be.fullname" . }}-policy
  labels:
    {{- include "care-be.labels" . | nindent 4 }}
spec:
  default:
    timeoutSec: {{ .Values.backendPolicy.timeoutSec }}
    connectionDraining:
      drainingTimeoutSec: {{ .Values.backendPolicy.drainingTimeoutSec }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "care-be.fullname" . }}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "care-be.fullname" . }}-health
  labels:
    {{- include "care-be.labels" . | nindent 4 }}
spec:
  default:
    checkIntervalSec: {{ .Values.backendPolicy.healthCheck.checkIntervalSec }}
    timeoutSec: {{ .Values.backendPolicy.healthCheck.timeoutSec }}
    healthyThreshold: {{ .Values.backendPolicy.healthCheck.healthyThreshold }}
    unhealthyThreshold: {{ .Values.backendPolicy.healthCheck.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.backendPolicy.healthCheck.port }}
        requestPath: {{ .Values.backendPolicy.healthCheck.path }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "care-be.fullname" . }}
{{- end }}
