{{- if and .Values.secret.enabled .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "care-be.fullname" . }}-secret
  labels:
    {{- include "care-be.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ quote $value }}
  {{- end }}
{{- end }}

