{{- if and (eq .Values.global.cloudProvider "gcp") (tpl (.Values.backendPolicy.enabled | toString) .) }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "dcm4chee.fullname" . }}-nginx-policy
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
spec:
  default:
    timeoutSec: {{ .Values.backendPolicy.timeoutSec }}
    connectionDraining:
      drainingTimeoutSec: {{ .Values.backendPolicy.drainingTimeoutSec }}
    logging:
      enabled: {{ .Values.global.backendPolicy.logging.enabled }}
      {{- if .Values.global.backendPolicy.logging.enabled }}
      sampleRate: {{ .Values.global.backendPolicy.logging.sampleRate | int }}
      {{- end }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "dcm4chee.fullname" . }}-nginx
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "dcm4chee.fullname" . }}-nginx-health
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
spec:
  default:
    checkIntervalSec: {{ .Values.backendPolicy.healthCheck.checkIntervalSec }}
    timeoutSec: {{ .Values.backendPolicy.healthCheck.timeoutSec }}
    healthyThreshold: {{ .Values.backendPolicy.healthCheck.healthyThreshold }}
    unhealthyThreshold: {{ .Values.backendPolicy.healthCheck.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.backendPolicy.healthCheck.port }}
        requestPath: {{ .Values.backendPolicy.healthCheck.path }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "dcm4chee.fullname" . }}-nginx
{{- end }}
