apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcm4chee.fullname" . }}-nginx
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"{{ .Values.nginx.service.port }}":{}}}'
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "dcm4chee.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
