apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcm4chee.fullname" . }}-arc
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
    app.kubernetes.io/component: arc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.arc.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "dcm4chee.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: arc
