apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcm4chee.fullname" . }}-ohif
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
    app.kubernetes.io/component: ohif
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ohif.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "dcm4chee.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ohif
