apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcm4chee.fullname" . }}-ldap
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ldap.service.port }}
      targetPort: 389
      protocol: TCP
      name: ldap
  selector:
    {{- include "dcm4chee.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
