{{- if tpl (.Values.httpRoute.enabled | toString) . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "care-fe.fullname" . }}-route
  labels:
    {{- include "care-fe.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ tpl .Values.httpRoute.gatewayName . }}
      sectionName: https
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "care-fe.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
